infraMgr:
  git:
    repository: git@github.com:th2-net/th2-infra-demo-configuration.git
    httpAuthUsername: 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
    httpAuthPassword: ''


rabbitmq:
 host: 192.168.49.2
  prometheus:
    operator:
      enabled: false
  persistentVolume:
    enabled: true
    storageClass: local-storage
    size: 10Gi
  ingress:
    enabled: true
    hostName:

cassandra:
  internal: false
  host:  host.minikube.internal
  cluster:
    datacenter: datacenter1

