name: Unittest box chart
on:
  pull_request:
    paths:
      - "box-chart/**"
      - ".github/workflows/unittest-box-chart.yaml"
  workflow_dispatch:

jobs:
  Unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.1
      
      - name: run unit test
        run: |
          helm plugin install https://github.com/quintush/helm-unittest
          helm unittest -q CHART box-chart